# Generated by Django 6.0.5 on 2026-05-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='codigo_expiracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='codigo_recuperacao',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
