# Generated by Django 6.0.5 on 2026-05-17 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_customuser_codigo_expiracao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('capacidade_maxima', models.IntegerField(default=4)),
                ('alunos', models.ManyToManyField(blank=True, related_name='aulas_agendadas', to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas_ministradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
