# Generated by Django 6.0.5 on 2026-05-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='primeiro_acesso',
            field=models.BooleanField(default=True),
        ),
    ]
