# Generated by Django 6.0.5 on 2026-05-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_customuser_primeiro_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
