# Generated by Django 6.0.5 on 2026-05-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_customuser_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='lgpd_consentimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
